### ISSUE TITLE
question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [BinTianqi/OwnDroid#89]
The scanner at IzzyOnDroid just reported:

```
! repo/com.bintianqi.owndroid_35.apk declares sensitive permission(s):
  android.permission.ACCESS_FINE_LOCATION android.permission.ACCESS_COARSE_LOCATION
! repo/com.bintianqi.owndroid_35.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Could you please clarify what the location permission is needed/used for?

Concerning `DEPENDENCY_INFO_BLOCK`, that's easily avoided with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by BinTianqi** [comment]
OwnDroid need location permission to get saved Wi-Fi list. It doesn't read user's geolocation.

I use gradle in bash to build OwnDroid v6.3 apk and gradle signed it automatically. The reason why dependency info block appears in the apk maybe the `com.google.accompanist:accompanist-permissions` dependency I add 5 days ago. I will disable dependency metadata later.

**Comment by IzzySoft** [comment]
> OwnDroid need location permission to get saved Wi-Fi list. It doesn't read user's geolocation.

Thanks! Added that to the "green list":

```yaml
    android.permission.REQUEST_INSTALL_PACKAGES: this app is intended a.o. to manage your apps
    android.permission.REQUEST_DELETE_PACKAGES: this app is intended a.o. to manage your apps
    android.permission.QUERY_ALL_PACKAGES: this app is intended a.o. to manage your apps
    android.permission.ACCESS_FINE_LOCATION: needed to access the saved Wi-Fi list
    android.permission.ACCESS_COARSE_LOCATION: needed to access the saved Wi-Fi list
```

> I will disable dependency metadata later.

Thanks! And the reason it's in there in the first place is that some version of AGP started to put it there by default (because Google wants it for their PlayStore – which, as you know, they consider to be the one-and-only "safe" place to publish apps).
